algoritmo "Somador"

var
   N, S: Inteiro
   Resp: Caractere
inicio
      S <- 0
      Resp <- "S"
      Enquanto (Resp = "S") faca        // enquanto o valor lógico for similar ao "DECLARADO", o programa repetirá sucessivamente
          Escreva ("Digite o valor ==> ")
          Leia (N)
          S <- s + n
          Escreva ("Você quer continuar? [S/N] ")
          Leia (resp)
      FimEnquanto
      Escreval ("A soma de todos os valores digitados é ", S)
fimalgoritmo
