algoritmo "Somador"

var
   N, S: Inteiro
   Resp: Caractere
inicio
      S <- 0
      Repita   // Tudo se repetirá " ATÉ " ocorrer o determinado na variável...
          Escreva ("Digite o valor ==> ")
          Leia (N)
          S <- s + n
          Escreva ("Você quer continuar? [S/N] ")
          Leia (resp)
      Ate (Resp = "N")  //... que se encontra NESTA linha
      Escreval ("A soma de todos os valores digitados é ", S)
fimalgoritmo
