algoritmo "Tamanho_Peça"

var
    P1, P2, P3, Padrao:real
inicio
     Escreva ("Digite o Tamanho da peça1 ")
     Leia(P1)
     Escreva("Digite o Tamanho da peça2 ")
     Leia(P2)
     Escreva("Digite o Tamanho da peça3 ")
     Leia(P3)
             // Testando se as pçs 1,2,3 estão padronizada
     Padrao <- 40
     Escreval("Peça1 ", p1 = padrao)
     Escreval("Peça2 ", P2 = padrao)
     Escreval("Peça3 ", P3 = padrao)
     

fimalgoritmo
